### ISSUE TITLE
debug modules 

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/tinker#13]
debug logging:
- [ ] a multiple tags based approach to log failures or proof information during evaluation.
- [ ] possible tags
- [ ] structure view of a logging information (have a chat with Andrius for the proof logging sometimes)

tag
- [ ] tactic failures: no binding atomics; failed application
- [ ] goal type failures with deferent levels (e.g. just failures, only active branch, all)
- [ ] partition failures
- [ ] branching failures
-  [ ] goal information

eval option:
- [ ]  run until (break points)
- [ ] deactive goal node (choose a goal node and not to run it) 
- [ ] step over
- [ ] step into

**Comment by plebras** [comment]
see #46 and #37
