### ISSUE TITLE
show connection status

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/tinker#27]
to have a status bar to show the connection status, e.g. whether is connected (maybe a green or red light icon), and which theorem prover is connected,

**Comment by plebras** [comment]
it is somehow implemented : 
- a connect button is located near the eval options
- when disconnected, arrows (showing message exchange) are empty
- if user clicks the button they are still empty while connecting
- when fully connected they are full
@lyhlbyl what's your though on this ? should we have a message box clearly stating it ? (maybe this message box could be extended to show other messages such as "prover swithed branch")
