### ISSUE TITLE
aggressive error messages when atomic tactics not existing

### ISSUE THREAD

**Issue by ggrov** [ggrov/tinker#60]
The error messages when I introduce an atomic tactic is very aggressive - e.g. I cannot even delete a node if the atomic method does not exists as all that happens is I get the error message again. Fine to have a warning when it first introduced but that should be it - e.g. what if I wanted to add it later but draw the graph first?. Maybe we could just have a red font for this case (or scribbled underscore as in Eclipse)?

**Comment by plebras** [comment]
That should actually have been fixed. Although it is probably not in the build yet. I will check that.
