### ISSUE TITLE
When selecting hierarchical tactic the children should be automatically displayed

### ISSUE THREAD

**Issue by ggrov** [ggrov/tinker#68]
The user should not need to having to select it from drop down menu

**Comment by plebras** [comment]
Do you mean automatically displaying the subgraph when selecting a graph tactic ? My worry is it may annoy the user who wanted to keep the subgraph currently displayed.
There is however an existing shortcut : right-click on the graph tactic node and select "inspect tactic" in the context menu. Do you think it could be enough ?

**Comment by ggrov** [comment]
Yes, that's what I meant. I think it is more annoying having to manually
select the graph.
